apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-pv
  labels:
    type: dev-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/docker"