apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    type: redis-pod
spec:
  containers:
    - name: redis-c
      image: redis:latest
      resources:
        requests:
          cpu: 100m
          memory: 50Mi
        limits:
          cpu: 120m
          memory: 100Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disktype
                operator: In
                values:
                  - ssd