apiVersion: apps/v1 
kind: Deployment
metadata:
  name: busybox-dpt
  labels:
    type: busybox-dpt
spec:
  selector:
    matchLabels:
      type: busybox
  template:
    metadata:
      name: busybox 
      labels:
        type: busybox 
    spec:
      containers:
        - name: busybox 
          image: busybox:latest
          command: ["/bin/sh", "-c", "while true; do wget http://cluster-ip-svc:80 && sleep 5; done"]