apiVersion: v1 
kind: Pod
metadata:
  name: redis-pod
  labels:
    type: redis-pod
spec:
  containers:
    - name: redis-1
      image: redis:latest
      resources:
        requests:
          cpu: 100m
          memory: 50Mi
        limits:
          cpu: 150m
          memory: 100Mi
  
  tolerations:
    - key: gpu
      value: "true"
      operator: Equal